services:
  - type: web
    name: plant-pulse
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false --server.fileWatcherType=none
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2

